"""empty message

Revision ID: 5dea4a69f196
Revises: 180cd4e5971b
Create Date: 2019-12-02 22:13:50.297273

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5dea4a69f196'
down_revision = '180cd4e5971b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notes', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notes')
    # ### end Alembic commands ###
